### PR TITLE
[PR] Add cookie domain text field

### PR DESCRIPTION
**Pull request by jeremyBass**
Set to accommodate the need to set up a cookie that is not under the domain of `.wsu.edu` in the platform.

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Rather than rely on an input, we could match the site's domain against `wsu.edu` and switch on the fly when needed.

**Comment by jeremyBass** [comment]
I thought about that , but we have to then also come up with a way to know if we need it as `.wsu.edu` or `wsu.edu` with out knowing, and that I don't think we can detect in a way that would always work

**Comment by jeremyfelt** [comment]
Is there ever a case where `randomwsuaffiliate.org` should have a cookie domain of `.wsu.edu` set?

**Comment by jeremyBass** [comment]
no but they may need `.randomwsuaffiliate.org`

**Comment by jeremyfelt** [comment]
Would setting it to always be `.randomwsuaffiliate.org` cause issues with tracking? We do that with `wsu.edu` now.

**Comment by jeremyBass** [comment]
yes, and why we can't know for sure if the subdomain donation is needed or not.  `.` is an important part here but only if your not on the root url, which we don't know if we will not have that happen.

**Pull request merged**
